workflows:
  ios-capacitor-build:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.wortmanstores.jackflash"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      
      - name: Capacitor sync
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      
      - name: Set up provisioning profiles
        script: |
          xcode-project use-profiles
      
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release
    
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true